spring:
  application:
    name: sparta-scheduling
  datasource:
    url: jdbc:mysql://localhost:3306/sparta_scheduling
    username: root
    password: wndud2Rj~!!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    open-in-view: false

jwt:
  secret:
    key: "7Iqk7YyM66W07YOA7L2U65Sp7YG065+9U3ByaW5n6rCV7J2Y7Yqc7YSw7LWc7JuQ67mI7J6F64uI64ukLg=="